version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
    build_and_test: test
      executor: node/default 
      steps:
        - checkout
        node/install-packages:
            pkg-manager: npm
        - run:
          command: npm install
        - name: Install dependencies
        - run:
          command: npm run think
        - name: RunThink
        - run:
          command: npm run meta
        - name: RunMeta