name: Altarius data
on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 10 * * *"
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: RunThink
        continue-on-error: true
        run: npm run think
      - name: RunMeta
        continue-on-error: true
        run: npm run meta
